//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BBKV2.Servicebb {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceBBintemSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceBBintem : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback mayOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_shiftOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_shiftMayBBOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Mesid_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrinterOperationCompleted;
        
        private System.Threading.SendOrPostCallback FinishOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_BarcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Mesid_list_InlaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback Print_BBOperationCompleted;
        
        private System.Threading.SendOrPostCallback Print_BB_AgainOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceBBintem() {
            this.Url = "http://198.1.10.133:9100/ServiceBBintem.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event mayCompletedEventHandler mayCompleted;
        
        /// <remarks/>
        public event Get_shiftCompletedEventHandler Get_shiftCompleted;
        
        /// <remarks/>
        public event Get_shiftMayBBCompletedEventHandler Get_shiftMayBBCompleted;
        
        /// <remarks/>
        public event Get_Mesid_listCompletedEventHandler Get_Mesid_listCompleted;
        
        /// <remarks/>
        public event PrinterCompletedEventHandler PrinterCompleted;
        
        /// <remarks/>
        public event FinishCompletedEventHandler FinishCompleted;
        
        /// <remarks/>
        public event Get_BarcodeCompletedEventHandler Get_BarcodeCompleted;
        
        /// <remarks/>
        public event Get_Mesid_list_InlaiCompletedEventHandler Get_Mesid_list_InlaiCompleted;
        
        /// <remarks/>
        public event Print_BBCompletedEventHandler Print_BBCompleted;
        
        /// <remarks/>
        public event Print_BB_AgainCompletedEventHandler Print_BB_AgainCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Login(string empno) {
            object[] results = this.Invoke("Login", new object[] {
                        empno});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string empno) {
            this.LoginAsync(empno, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string empno, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        empno}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/may", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] may() {
            object[] results = this.Invoke("may", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void mayAsync() {
            this.mayAsync(null);
        }
        
        /// <remarks/>
        public void mayAsync(object userState) {
            if ((this.mayOperationCompleted == null)) {
                this.mayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmayOperationCompleted);
            }
            this.InvokeAsync("may", new object[0], this.mayOperationCompleted, userState);
        }
        
        private void OnmayOperationCompleted(object arg) {
            if ((this.mayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mayCompleted(this, new mayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_shift", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_shift() {
            object[] results = this.Invoke("Get_shift", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_shiftAsync() {
            this.Get_shiftAsync(null);
        }
        
        /// <remarks/>
        public void Get_shiftAsync(object userState) {
            if ((this.Get_shiftOperationCompleted == null)) {
                this.Get_shiftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_shiftOperationCompleted);
            }
            this.InvokeAsync("Get_shift", new object[0], this.Get_shiftOperationCompleted, userState);
        }
        
        private void OnGet_shiftOperationCompleted(object arg) {
            if ((this.Get_shiftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_shiftCompleted(this, new Get_shiftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_shiftMayBB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_shiftMayBB() {
            object[] results = this.Invoke("Get_shiftMayBB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_shiftMayBBAsync() {
            this.Get_shiftMayBBAsync(null);
        }
        
        /// <remarks/>
        public void Get_shiftMayBBAsync(object userState) {
            if ((this.Get_shiftMayBBOperationCompleted == null)) {
                this.Get_shiftMayBBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_shiftMayBBOperationCompleted);
            }
            this.InvokeAsync("Get_shiftMayBB", new object[0], this.Get_shiftMayBBOperationCompleted, userState);
        }
        
        private void OnGet_shiftMayBBOperationCompleted(object arg) {
            if ((this.Get_shiftMayBBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_shiftMayBBCompleted(this, new Get_shiftMayBBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Mesid_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_Mesid_list(string Machno) {
            object[] results = this.Invoke("Get_Mesid_list", new object[] {
                        Machno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Mesid_listAsync(string Machno) {
            this.Get_Mesid_listAsync(Machno, null);
        }
        
        /// <remarks/>
        public void Get_Mesid_listAsync(string Machno, object userState) {
            if ((this.Get_Mesid_listOperationCompleted == null)) {
                this.Get_Mesid_listOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Mesid_listOperationCompleted);
            }
            this.InvokeAsync("Get_Mesid_list", new object[] {
                        Machno}, this.Get_Mesid_listOperationCompleted, userState);
        }
        
        private void OnGet_Mesid_listOperationCompleted(object arg) {
            if ((this.Get_Mesid_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Mesid_listCompleted(this, new Get_Mesid_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Printer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Printer() {
            object[] results = this.Invoke("Printer", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void PrinterAsync() {
            this.PrinterAsync(null);
        }
        
        /// <remarks/>
        public void PrinterAsync(object userState) {
            if ((this.PrinterOperationCompleted == null)) {
                this.PrinterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrinterOperationCompleted);
            }
            this.InvokeAsync("Printer", new object[0], this.PrinterOperationCompleted, userState);
        }
        
        private void OnPrinterOperationCompleted(object arg) {
            if ((this.PrinterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrinterCompleted(this, new PrinterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Finish", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Finish(string tenkeo, string mesid, string machno) {
            object[] results = this.Invoke("Finish", new object[] {
                        tenkeo,
                        mesid,
                        machno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FinishAsync(string tenkeo, string mesid, string machno) {
            this.FinishAsync(tenkeo, mesid, machno, null);
        }
        
        /// <remarks/>
        public void FinishAsync(string tenkeo, string mesid, string machno, object userState) {
            if ((this.FinishOperationCompleted == null)) {
                this.FinishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinishOperationCompleted);
            }
            this.InvokeAsync("Finish", new object[] {
                        tenkeo,
                        mesid,
                        machno}, this.FinishOperationCompleted, userState);
        }
        
        private void OnFinishOperationCompleted(object arg) {
            if ((this.FinishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FinishCompleted(this, new FinishCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Barcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_Barcode(string mesid, string machno) {
            object[] results = this.Invoke("Get_Barcode", new object[] {
                        mesid,
                        machno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_BarcodeAsync(string mesid, string machno) {
            this.Get_BarcodeAsync(mesid, machno, null);
        }
        
        /// <remarks/>
        public void Get_BarcodeAsync(string mesid, string machno, object userState) {
            if ((this.Get_BarcodeOperationCompleted == null)) {
                this.Get_BarcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_BarcodeOperationCompleted);
            }
            this.InvokeAsync("Get_Barcode", new object[] {
                        mesid,
                        machno}, this.Get_BarcodeOperationCompleted, userState);
        }
        
        private void OnGet_BarcodeOperationCompleted(object arg) {
            if ((this.Get_BarcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_BarcodeCompleted(this, new Get_BarcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Mesid_list_Inlai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_Mesid_list_Inlai(string Machno) {
            object[] results = this.Invoke("Get_Mesid_list_Inlai", new object[] {
                        Machno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Mesid_list_InlaiAsync(string Machno) {
            this.Get_Mesid_list_InlaiAsync(Machno, null);
        }
        
        /// <remarks/>
        public void Get_Mesid_list_InlaiAsync(string Machno, object userState) {
            if ((this.Get_Mesid_list_InlaiOperationCompleted == null)) {
                this.Get_Mesid_list_InlaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Mesid_list_InlaiOperationCompleted);
            }
            this.InvokeAsync("Get_Mesid_list_Inlai", new object[] {
                        Machno}, this.Get_Mesid_list_InlaiOperationCompleted, userState);
        }
        
        private void OnGet_Mesid_list_InlaiOperationCompleted(object arg) {
            if ((this.Get_Mesid_list_InlaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Mesid_list_InlaiCompleted(this, new Get_Mesid_list_InlaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Print_BB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Print_BB(string tenkeo, string Machno, string printername, string ca, string usrno, string candao, string Soluong, string mesid, string pallet, string mac_pda, string OEM, string depno) {
            object[] results = this.Invoke("Print_BB", new object[] {
                        tenkeo,
                        Machno,
                        printername,
                        ca,
                        usrno,
                        candao,
                        Soluong,
                        mesid,
                        pallet,
                        mac_pda,
                        OEM,
                        depno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Print_BBAsync(string tenkeo, string Machno, string printername, string ca, string usrno, string candao, string Soluong, string mesid, string pallet, string mac_pda, string OEM, string depno) {
            this.Print_BBAsync(tenkeo, Machno, printername, ca, usrno, candao, Soluong, mesid, pallet, mac_pda, OEM, depno, null);
        }
        
        /// <remarks/>
        public void Print_BBAsync(string tenkeo, string Machno, string printername, string ca, string usrno, string candao, string Soluong, string mesid, string pallet, string mac_pda, string OEM, string depno, object userState) {
            if ((this.Print_BBOperationCompleted == null)) {
                this.Print_BBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrint_BBOperationCompleted);
            }
            this.InvokeAsync("Print_BB", new object[] {
                        tenkeo,
                        Machno,
                        printername,
                        ca,
                        usrno,
                        candao,
                        Soluong,
                        mesid,
                        pallet,
                        mac_pda,
                        OEM,
                        depno}, this.Print_BBOperationCompleted, userState);
        }
        
        private void OnPrint_BBOperationCompleted(object arg) {
            if ((this.Print_BBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Print_BBCompleted(this, new Print_BBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Print_BB_Again", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Print_BB_Again(string usrno, string Machno, string barcode, string mesid, string soluong, string printername, string tenkeo) {
            object[] results = this.Invoke("Print_BB_Again", new object[] {
                        usrno,
                        Machno,
                        barcode,
                        mesid,
                        soluong,
                        printername,
                        tenkeo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Print_BB_AgainAsync(string usrno, string Machno, string barcode, string mesid, string soluong, string printername, string tenkeo) {
            this.Print_BB_AgainAsync(usrno, Machno, barcode, mesid, soluong, printername, tenkeo, null);
        }
        
        /// <remarks/>
        public void Print_BB_AgainAsync(string usrno, string Machno, string barcode, string mesid, string soluong, string printername, string tenkeo, object userState) {
            if ((this.Print_BB_AgainOperationCompleted == null)) {
                this.Print_BB_AgainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrint_BB_AgainOperationCompleted);
            }
            this.InvokeAsync("Print_BB_Again", new object[] {
                        usrno,
                        Machno,
                        barcode,
                        mesid,
                        soluong,
                        printername,
                        tenkeo}, this.Print_BB_AgainOperationCompleted, userState);
        }
        
        private void OnPrint_BB_AgainOperationCompleted(object arg) {
            if ((this.Print_BB_AgainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Print_BB_AgainCompleted(this, new Print_BB_AgainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mayCompletedEventHandler(object sender, mayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_shiftCompletedEventHandler(object sender, Get_shiftCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_shiftCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_shiftCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_shiftMayBBCompletedEventHandler(object sender, Get_shiftMayBBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_shiftMayBBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_shiftMayBBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_Mesid_listCompletedEventHandler(object sender, Get_Mesid_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Mesid_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Mesid_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PrinterCompletedEventHandler(object sender, PrinterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrinterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrinterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void FinishCompletedEventHandler(object sender, FinishCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FinishCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FinishCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_BarcodeCompletedEventHandler(object sender, Get_BarcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_BarcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_BarcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_Mesid_list_InlaiCompletedEventHandler(object sender, Get_Mesid_list_InlaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Mesid_list_InlaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Mesid_list_InlaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Print_BBCompletedEventHandler(object sender, Print_BBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Print_BBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Print_BBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Print_BB_AgainCompletedEventHandler(object sender, Print_BB_AgainCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Print_BB_AgainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Print_BB_AgainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591